---
# May be overridden by values in settings_local.yml

defaults:
  issues_url: https://github.com/simonbaird/tiddlyhost/issues
  default_plan_name: basic
  minimum_password_length: 8

  # Let's turn these off for now and see what tags appear organically
  #hub_tags:
  #  twplugins:
  #    :title: TiddlyWiki Plugin Hub
  #    :tag: TiddlyWikiPlugin
  #    :description: Sites containing useful plugins created by the TiddlyWiki community.
  #  twdocs:
  #    :title: TiddlyWiki Docs Hub
  #    :tag: TiddlyWikiDoc
  #    :description: Sites container documentation, tutorials, and other informational resources related to TiddlyWiki.

  banner_message:
    :icon: exclamation-triangle
    :html: |
      Beware, Tiddlyhost is in the early stages of development and may be
      unstable. If you experience problems or have a feature suggestion, please create an
      issue in <a href="https://github.com/simonbaird/tiddlyhost/issues">GitHub</a>.

development:
  url_defaults:
    :host: tiddlyhost.local
    :port: 3333
    :protocol: <%= ENV['START_WITHOUT_SSL'] == 'yes' ? 'http' : 'https' %>

test:
  url_defaults:
    :host: example.com
    :protocol: http

production:
  url_defaults:
    :host: tiddlyhost.com
    :protocol: https
