---
# May be overridden by values in settings_local.yml

defaults:
  issues_url: https://github.com/simonbaird/tiddlyhost/issues

development:
  url_defaults:
    :host: tiddlyhost.local
    :port: 3000
    :protocol: https

test:
  url_defaults:
    :host: example.com
    :protocol: http

production:
  url_defaults:
    :host: tiddlyhost.com
    :protocol: https
