---
# May be overridden by values in settings_local.yml

defaults:
  issues_url: https://github.com/simonbaird/tiddlyhost/issues
  default_plan_name: basic
  minimum_password_length: 8

  hub_tags:
    twplugins:
      :title: TiddlyWiki Plugin Hub
      :tag: TiddlyWikiPlugin
    twdocs:
      :title: TiddlyWiki Docs Hub
      :tag: TiddlyWikiDoc

development:
  url_defaults:
    :host: tiddlyhost.local
    :port: 3333
    :protocol: <%= ENV['START_WITHOUT_SSL'] == 'yes' ? 'http' : 'https' %>

test:
  url_defaults:
    :host: example.com
    :protocol: http

production:
  url_defaults:
    :host: tiddlyhost.com
    :protocol: https
