---
# May be overridden by values in settings_local.yml

defaults:
  github_url: https://github.com/simonbaird/tiddlyhost
  issues_url: https://github.com/simonbaird/tiddlyhost/issues
  faq_url: https://github.com/simonbaird/tiddlyhost/wiki/FAQ
  create_issue_url: https://github.com/simonbaird/tiddlyhost/issues/new
  support_email: tiddlyhost@gmail.com
  support_email_name: Tiddlyhost Support
  default_plan_name: basic
  default_empty_name: tw5
  minimum_password_length: 8

  #banner_message:
  #  :icon: exclamation-triangle
  #  :html: |
  #    Beware, Tiddlyhost is in the early stages of development and may be
  #    unstable. If you experience problems or have a feature suggestion, please create an
  #    issue in <a href="https://github.com/simonbaird/tiddlyhost/issues">GitHub</a>.

development:
  url_defaults:
    :host: tiddlyhost.local
    :protocol: https

  tiddlyspot_host: tiddlyspot.local

test:
  url_defaults:
    :host: example.com
    :protocol: http

  tiddlyspot_host: tiddlyspot-example.com

production:
  url_defaults:
    :host: tiddlyhost.com
    :protocol: https

  tiddlyspot_host: tiddlyspot.com
