---
# May be overridden by values in settings_local.yml

defaults:
  github_url: https://github.com/simonbaird/tiddlyhost
  issues_url: https://github.com/simonbaird/tiddlyhost/issues
  faq_url: https://github.com/simonbaird/tiddlyhost/wiki/FAQ
  create_issue_url: https://github.com/simonbaird/tiddlyhost/issues/new
  devise_mailer_sender: '"Tiddlyhost" <tiddlyhost@gmail.com>'
  support_email: simon.baird@gmail.com
  support_email_name: Simon Baird
  default_plan_name: basic
  default_empty_name: tw5
  minimum_password_length: 8
  hub_tag_tab_count: 6
  db_host: <%= is_in_container ? "db" : "localhost" %>

  #banner_message:
  #  :icon: exclamation-triangle
  #  :html: |
  #    Beware, Tiddlyhost is in the early stages of development and may be
  #    unstable. If you experience problems or have a feature suggestion, please create an
  #    issue in <a href="https://github.com/simonbaird/tiddlyhost/issues">GitHub</a>.


development:
  url_defaults:
    :host: tiddlyhost.local
    # By "in container" we actually mean running with
    # docker-compose up with the nginx front end
    :protocol: <%= is_in_container ? "https" : "http" %>
    :port: <%= is_in_container ? nil : 3333 %>

  tiddlyspot_host: tiddlyspot.local

test:
  url_defaults:
    :host: example.com
    :protocol: http

  tiddlyspot_host: tiddlyspot-example.com

production:
  url_defaults:
    :host: tiddlyhost.com
    #:host: tiddlyhost.local
    :protocol: https

  tiddlyspot_host: tiddlyspot.com
  #tiddlyspot_host: tiddlyspot.local
